name = "Khlebko"
license = "MIT"
description = "Personal page, powered by Hugo"
homepage = "https://github.com/nurlansu/hugo-sustain"
tags = ["minimal", "responsive"]
features = ["responsive", "syntax highlighting"]
min_version = 0.17

[author]
  name = "Pavel Khlebko"
  homepage = "https://khlebko.com"
